In [10]:
import numpy as np
import matplotlib.pyplot as plt

# 1

In [11]:
M1 = np.array([[23, 50],
               [7, 12]])
M2 = np.array([[57,67],
               [99,43]])
M3 = np.array([[75,21],
               [57,12]])
M4 = np.array([[87,26],
               [18,84]])

tensor = np.array([[M1, M2], [M3,M4]])
tensor

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]]],


       [[[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [12]:
tensor.shape

(2, 2, 2, 2)

In [13]:
tensor.ndim

4

# 2

In [14]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])

B = np.array([17,22,19])

A * B

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

# 3

In [15]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])

In [16]:
#TRANSPOSE
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [17]:
#DETERMINANT
np.linalg.det(A)

131344.0000000002

In [18]:
#INVERSE
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])